#! /bin/bash

format='{%n  "commit": "%H",%n  "author": "%an",%n  "email": "%ae",%n  "date": "%ad",%n  "message": "%s"%n}'  
GITPATH=$(git rev-parse --show-toplevel)
COMMITINFO="$GITPATH/nixos/.lastcommit.json"

echo "Requesting sudo to write to file ${COMMITINFO}"
git log -1 --pretty=format:"${format}" | sudo tee "${COMMITINFO}"
git add --intent-to-add "${COMMITINFO}"
git update-index --assume-unchanged "${COMMITINFO}"


echo -e "\nPost-hook wrote to ${COMMITINFO}"
