#! /bin/bash
######## CONFIGURABLES ########
mapfile PROHIBITEDNAMES < <(echo -e ".*secrets.nix")
HEADER_WIDTH=30

# Colors
RED="[1;31m"
YELLOW="[38;5;214m"
GREEN="[1;32m"

HEDCOL="[0;36m"

#echo -e "\033$RED RED"
#echo -e "\033$YELLOW YELLOW"
#echo -e "\033$GREEN GREEN \033[0m"

#SECTION_HEADER="\033[0;36m====\033[0m%s\033[0;36m====\033[0m\n"
# Write function to center justify this.







######## SETUP ##########

GITPATH=$( git rev-parse --show-toplevel )

# Get path to secrets, and do detection/error handling for that.
mapfile SECRETPATH < <( find $GITPATH -name secrets.nix )
if [[ "${#SECRETPATH[@]}" -ne 1 ]] then
    echo "Error. More than one filepath with name 'secrets.nix' found."
    for p in ${SECRETPATH[@]}; do echo ">" $p; done 
    exit 1
fi

# Get all paths staged for commit.
mapfile STAGED < <(\
    git diff --name-only --cached |
    xargs -I{} echo -n "$GITPATH/{} "
)

# If run as 'pre-commit all', add everything except the prohibited files.
if [[ $1 == "all" ]]; then
    declare -a TOCHECK
    for TF in $(git ls-files $GITPATH); do
        for PF in ${PROHIBITEDNAMES[@]}; do
            if [[ "$TF" =~ $PF ]]; then
                SKIP=1
            fi
        done
        if [[ -n $SKIP ]]; then
            unset SKIP
        else
            TOCHECK+=($TF)
        fi
    done
else
    # Otherwise, just check staged files
    TOCHECK=("${STAGED[@]}") 
fi


# Load and format variables from nixfile
mapfile NIXVARS < <( echo -e $( nix eval --impure --expr "
    let l = (import <nixpkgs> {}).lib;
    in l.strings.concatMapStringsSep \"\\n\" toString (
        l.lists.flatten( 
            l.collect ( a: !builtins.isAttrs a) (import $SECRETPATH {})
        )
    )
" ) | tr -d '"' )
#echo "${NIXVARS[@]}"

prompt_confirm() {
  for ((count=0; count<20 ; count++)); do
    read -r -N 1 -p "$1 [y/n]: " REPLY < /dev/tty

    case $REPLY in
      [yY]) echo ; return 0 ;;
      [nN]) echo ; return 1 ;;
      *) printf '\033[31m '\''%s'\'' %s \n\033[0m' "$REPLY" "invalid input"
    esac 
  done  
  if [[ ! "$input" =~ ^[YyNn]$  ]]; then
	echo "FAILED TO GATHER INPUT."
    exit 1
  fi
}

centered_header() {
    local title="$1"
    local width="$HEADER_WIDTH"
    local title_length=${#title}

    # Calculate the total padding needed (in equal signs)
    local padding=$(( (width - title_length - 4) / 2 ))

    # Ensure padding is not negative
    if (( padding < 0 )); then
        padding=0
    fi

	if (( title_length % 2 )); then
		r_padding=$(( padding+1 ))
    else
		r_padding=$padding
    fi
	


    # Generate the padded header using equal signs for padding
    local l_pad="$(printf '=%.0s' $(seq 1 $padding))"
	local r_pad="$(printf '=%.0s' $(seq 1 $r_padding))"

    printf "\033[0;36m%s\033[0m\033[0;37m %s \033[0m\033[0;36m%s\033[0m\n" "$l_pad" "$title" "$r_pad"
}


##### CHECKING #####
EXIT=0

echo "Script is: $0 running using $$ PID"
echo "Current shell used within the script is: `readlink /proc/$$/exe`"

script_shell="$(readlink /proc/$$/exe | sed "s/.*\///")"

echo -e "\nSHELL is = ${script_shell}\n"

#printf $SECTION_HEADER "FORBIDDEN FILE CHECK"
centered_header "FORBIDDEN FILE CHECK"
for PF in ${PROHIBITEDNAMES[@]}; do
    for SF in ${TOCHECK[@]}; do
        if [[ "$SF" =~ $PF ]]; then
            echo -e "File path '$SF' matched regex \033${RED}$PF\033[0m"
            FAIL=1

        else
            #echo " $SF != $PF"
            true
        fi
        done
done
if [[ -n $FAIL ]]; then
    EXIT=1
    unset FAIL
else
    echo -e "\033${GREEN}PASS\033[1;0m"
fi


centered_header "SECRET STRING CHECK"
for FILE in ${TOCHECK[@]}; do
    for VAR in ${NIXVARS[@]}; do
        if [[ $(grep -c "$VAR" "$FILE") -ne 0 ]]; then
            echo -e "\nFound prohibited string \033${RED}$VAR\033[0m in $FILE"
            echo "grep results: "
            echo -e "\033[0;36m======\033[0m"

            grep -n -C 3 --group-separator='======' --color=always \
            "$VAR" "$FILE"
            echo -e "\033[0;36m======\033[0m"
            FAIL=1
        fi
    done
done
if [[ -n $FAIL ]]; then
    EXIT=1
    unset FAIL
else
    echo -e "\033${GREEN}PASS\033[1;0m"
fi


centered_header "FLAKE ON LATEST"
flakepath="$(mktemp "flake.lock.XXXXXX" -p "/tmp" )"
fctmp="nix flake check 
			--output-lock-file $flakepath 
			--recreate-lock-file $GITPATH/nixos" 
flakecheck=$(echo $fctmp)

# Don't run if there's no internet.
if ping -c 1 8.8.8.8 > /dev/null 2>&1; then
	echo "Running $flakecheck"
	results=$(eval $flakecheck ) 
	if jd $flakepath $GITPATH/nixos/flake.lock > /dev/null; then
			echo -e "\033${GREEN}PASS\033[1;0m"
	else
			echo -e "\n \033${RED}Lockfile out of date\033[0m"
		echo -e "Generated lockfile at $flakepath with length $(wc -l $flakepath) lines"
			if prompt_confirm "Update lockfile?"; then
					echo "sudo cp:"
					sudo cp $flakepath $GITPATH/nixos/flake.lock
					echo -e "\033${GREEN}PASS\033[1;0m"

			else
					if prompt_confirm "Commit out of date lockfile?"; then
							echo -e "\033${YELLOW}TEST BYPASSED\033[0m"
					else
							echo -e "\033${RED}FAIL\033[0m"
							FAIL=1
					fi
			fi
	fi
else
  echo -e "\033${YELLOW}TEST BYPASSED:\033[0m NO INTERNET"
fi


if [[ -n $FAIL ]]; then
    EXIT=1
    unset FAIL
fi



# TODO: Add a check for the latest firmware either here or in the build setup?


exit $EXIT
